### ISSUE TITLE
Fix documentation and "no visible global function definition"

### ISSUE THREAD

**Issue by hofnerb** [boost-R/gamboostLSS#10]
see e.g. https://s3.amazonaws.com/archive.travis-ci.org/jobs/115008209/log.txt

Please note that I've merged some changes from patch to pkg and might have broken some more things. I'll try to look into this but you might also want to have a look.

**Comment by ja-thomas** [comment]
Note to self: 
This seems to have to do with the `evalq()` calls in `iBoost_inner()` and `iBoost_outer()`. 
I may have to rewrite all of them and pick everything from the environment seperately.

Instead of 
`evalq(u <- ngradient(y, fit, weights), ENV[[k]])`

`ENV[[k]][["u"]] <- ENV[[k]][["ngradient"]](ENV[[k]][["y"]],ENV[[k]][["fit"]], ENV[[k]][["weights"]])`

and so on....

Especially for iBoost_outer() the code will get really ugly.

**Comment by ja-thomas** [comment]
one other possibility to fix this is two wrap the undefined variables in `get()` functions. But thats also not a really nice solution.
